### ISSUE TITLE
Address already used in REST API tests

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#1]
In the tests I see some errors like:
```
127.0.0.1 - - [2018-03-12 18:15:52] "PUT /api/1/balance HTTP/1.1" 400 200 0.000960
.Traceback (most recent call last):
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 360, in serve_forever
    self.start()
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/pywsgi.py", line 1450, in init_socket
    StreamServer.init_socket(self)
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/server.py", line 127, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/server.py", line 138, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/Users/paul/Work/raiden-pathfinding-service/venv/lib/python3.6/site-packages/gevent/server.py", line 229, in _tcp_listener
    sock.bind(address)
OSError: [Errno 48] Address already in use: ('localhost', 5002)
Mon Mar 12 18:15:53 2018 <Greenlet at 0x1096baaf8: <bound method BaseServer.serve_forever of <WSGIServer at 0x1097482e8 address=localhost:5002>>> failed with OSError
```

**Comment by LefterisJP** [comment]
Can you specify which test it is you see this at?

**Comment by hackaugusto** [comment]
Please note that in MacOS it takes more time for the ports to become available for rebinding.

Here is how this is fixed by the Raiden tests:

https://github.com/raiden-network/raiden/blob/master/raiden/tests/fixtures/variables.py#L216-L258

**Comment by palango** [comment]
Thanks for the hint @hackaugusto
